apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-calc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-calc
  template:
    metadata:
      labels:
        app: web-calc
    spec:
      containers:
      - name: web-calc
        image: vivich007/web-calculator:latest
        ports:
        - containerPort: 8080

        
